apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feature

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
- name: docker.drtest0629.reisys.io/ui-test
  newTag: 0.0.6