apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: feature

nameSuffix: -feature-pipeline

resources:
- ../base

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: docker.jmeks2020.reisys.io/ui-test
  newTag: feature-pipeline-48
