apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo-ui2
  namespace: develop
spec:
  template:
    spec:
      containers:
        - name: demo-ui2
          env:
            - name: ENVIRONMENT
              value: develop
            - name: foo
              value: bar
