apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: develop

resources:
  - ../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: docker.jmeks2020.reisys.io/ui-test
    newTag: 0.0.6