apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo-ui2
  namespace: prod
spec:
  template:
    spec:
      containers:
        - name: demo-ui2
          env:
            - name: ENVIRONMENT
              value: prod
            - name: foo
              value: bar
