apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../base

patchesStrategicMerge:
- deployment-patch.yaml

images:
- name: docker.jmeks20.reisys.io/ui-test
  newTag: master-4
